global_exclude_dirs:
    - vendor
    - vendors
    - test
    - tests
    - Tests
    - lib/vendor
    - src/Sedona/SBORuntimeBundle/public/vendor

rules:
  symfony.dependency_injection.use_dir_file_constant:
    enabled: false
